apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumno-deployment
  labels:
    app: alumno-deployment
spec:
  selector:
    matchLabels:
      app: alumno-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: alumno-deployment
    spec:
      containers:
        - name: alumno
          image: totozudo/alumno-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/alumno
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: alumno-service
  labels:
    app: alumno-service
spec:
  selector:
    app: alumno-deployment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer

